---
x-airflow-common: &airflow-common
  image: ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_REPOSITORY}:${IMAGE_TAG}
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_CONN_USERNAME}:${POSTGRES_CONN_PASSWORD}@postgres:5432/${METADATA_DATABASE_NAME}
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_CONN_USERNAME}:${POSTGRES_CONN_PASSWORD}@postgres:5432/${CELERY_BACKEND_NAME}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    RUNNING_ENV: LOCAL_DOCKER
    AIRFLOW_CONN_POSTGRES_DB_YT_ELT: 'postgresql://${ELT_DATABASE_USERNAME}:${ELT_DATABASE_PASSWORD}@postgres:5432/${ELT_DATABASE_NAME}'
  volumes:
    - ./config:/opt/airflow/config
    - ./workflows:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./data/configs:/home/airflow/gcs/data/configs
    - ./data/MR-Mapungubwe_Park_Records/mapungubwe_park:/home/airflow/gcs/data
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
  user: '${AIRFLOW_UID}:0'
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
    cloudsql-source:
      condition: service_healthy

services:
  cloudsql-source:
    image: mysql:8.0
    container_name: mapungubwe_mock_cloud_sql
    environment:
      - MYSQL_ROOT_PASSWORD=${POSTGRES_CONN_PASSWORD}
      - MYSQL_DATABASE=${ELT_DATABASE_NAME}
      - MYSQL_USER=${ELT_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${ELT_DATABASE_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./utils/init_local_cloud_sql.sql:/docker-entrypoint-initdb.d/init_local_cloud_sql.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 2s
      retries: 5
    restart: always

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_CONN_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_CONN_PASSWORD}
      - PGOPTIONS=-c custom.elt_pass=${ELT_DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./utils/init_local_db.sql:/docker-entrypoint-initdb.d/init_local_db.sql
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${POSTGRES_CONN_USERNAME}',
          '-d',
          'postgres',
        ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:7.2-bookworm
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - '8080:8080'
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username ${AIRFLOW_WWW_USER_USERNAME} --password ${AIRFLOW_WWW_USER_PASSWORD} --firstname Recruiter --lastname User --role Admin --email reviewer@riskwatch.local && airflow webserver"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker
    restart: always

volumes:
  postgres-db-volume:
